services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-openai-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}   
      - DATABASE_URL=${DATABASE_URL} 
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge 